/*!

=========================================================
* Black Dashboard React v1.2.0
=========================================================

* Product Page: https://www.creative-tim.com/product/black-dashboard-react
* Copyright 2020 Creative Tim (https://www.creative-tim.com)
* Licensed under MIT (https://github.com/creativetimofficial/black-dashboard-react/blob/master/LICENSE.md)

* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

*/

import React, { useState } from 'react';
// reactstrap components
import {
  Button,
  Card,
  CardHeader,
  CardBody,
  CardFooter,
  CardText,
  FormGroup,
  Form,
  Input,
  Row,
  Col,
} from "reactstrap";
import InfiniteScroll from "react-infinite-scroll-component";
import Popup from 'reactjs-popup';
import './app.css';
import axios from 'axios';
import { NFTStorage, File } from 'nft.storage'
import abi2 from './abi2.js'
import web3 from 'web3'

let client = new NFTStorage({ token: window.config1.nft_tokent_enc })
const address = window.config1.contract

function UserProfile() {
  const [aler,setaler] = React.useState(
    "none"
  )
  const [todos, setTodos] = useState([]);
  const [dis,setdis] = React.useState(
    false
  )
  let dic = {
    true:"none",
    false:"flex"

  }
  const [happen,sethappen] = React.useState(
    "Uploading to NFT.Storage"
  )
  const [sent,setsent] = useState(false);

  async function fetchImage(url){
    url = url.split('/');
   let link = url[2];
   let back = url[url.length-1];

   let data = await axios.get(`https://${link}.ipfs.dweb.link/${back}`)
   
   url = data.data.image.split("/");
   console.log("this is url"+ url)
   link = url[2]
   back = url[url.length-1];
   let urll = `https://${link}.ipfs.dweb.link/${back}`


   return urll



 }

 async function fetcher(){
   
await start()

 }
 async function asyncForEach(array, callback) {
  for (let index = 0; index < array.length; index++) {
    await callback(array[index], index, array);
  }
}


 const start = async () => {
  let todoss = []
  await asyncForEach(todos, async (elements) => {
    elements.url = await fetchImage(elements.uri)
    todoss.push(elements)
    console.log(elements)
  });
  setTodos(todoss);
  console.log('Done');
  setsent(true)
}


 
 
 

 async function handlecli(number){
    setdis(true)
    
    window.event.preventDefault();
    sethappen("Uploading to IPFS")
    const metadata = await client.store({
      name: todos[number].name,
      title: window.config.title,
      role : "participant",
      description:"Generated By Electica Hackthon Tempelate",
      address: todos[number].address,
      image: new File([await fetchImage(window.config.uri)], 'pinpie.jpg', { type: 'image/jpg' })
    })
    let url = metadata.url;
    sethappen("Calling Smart Contract")
    let contract = await new window.web3.eth.Contract(abi2,"0x894526204eE3F7d354ac763cfC2C76a0616DBF19");
    let a = await window.web3.eth.getAccounts()
    
    let {err,abc} = await contract.methods.addparticipant(todos[number].address,url).send({from:a[0]});
    if (err){
      alert("error occured")
    }
    let res = await axios.get(`https://participatehack.herokuapp.com/api/v1/users/approve?id=${todos[number]._id}`);
     

    
    setdis(false)
    setaler("flex")
    setTimeout(() => {
      setaler("none")
    }, 1000);
   
  }
  function Loader() {
    return (
  
      <div class="socket" style={{display:dic[!dis]}}>
        <div class="gel center-gel">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c1 r1">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c2 r1">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c3 r1">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c4 r1">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c5 r1">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c6 r1">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
  
        <div class="gel c7 r2">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
  
        <div class="gel c8 r2">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c9 r2">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c10 r2">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c11 r2">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c12 r2">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c13 r2">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c14 r2">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c15 r2">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c16 r2">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c17 r2">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c18 r2">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c19 r3">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c20 r3">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c21 r3">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c22 r3">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c23 r3">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c24 r3">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c25 r3">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c26 r3">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c28 r3">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c29 r3">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c30 r3">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c31 r3">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c32 r3">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c33 r3">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c34 r3">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c35 r3">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c36 r3">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
        <div class="gel c37 r3">
          <div class="hex-brick h1"></div>
          <div class="hex-brick h2"></div>
          <div class="hex-brick h3"></div>
        </div>
       <div class="blink_me">
       <h1 style={{paddingTop:"230px",textAlign:"center"}}>{happen}</h1>
       </div>
      </div>
  
    )
  }
 
  const fetchMoreData = async () => {

    if(!sent){
    const res = await axios.get(`https://participatehack.herokuapp.com/api/v1/nft?contract=${address}`);
    setTodos(res.data)
    fetcher()
    setsent(true)
    
   
    }
 


  };
  
  fetchMoreData()

  const approve = async (number) => {

    
  }
 
  

  
  


  return (
    <>
    <Loader></Loader>
      <div className="content">

        <div style={{ display: "flex", flexWrap: "wrap", justifyContent: "space-evenly",display:dic[dis] }}>
          {todos.map((i, index) => (
            <div key={index} style={{ width: "21%" }}>

              <Card className="card-user">
                <CardBody>
                  <CardText />

                  <div className="author">
                    <div className="block block-one" />
                    <div className="block block-two" />
                    <div className="block block-three" />
                    <div className="block block-four" />
                   
                      <div style={{height:"200px",width:"200px" 
                      }}>
                      <img src={todos[index].url} style={{paddingLeft:"0%",
                      textAlign:"center",alignSelf:"center"
                      }} />
                      </div>
                      <h5 className="title">Name : {todos[index].name}</h5>
                     
                 
                    <p className="description">Price : {todos[index].price}$</p>
                  </div>
                  <div className="card-description" style={{ textAlign: "center" }}>
                    Description : {todos[index].description}<br></br>
                    <br></br>
                    TokenId : {todos[index].tokenId}

                  </div>
              
                </CardBody>
            
              </Card>

            </div>

          ))}
           <div class="alert alert-success" style={{display:aler}} role="alert">
        
        Volunteer Added Successfully
      </div>
        </div>

       



      </div>
    </>
  );
}





export default UserProfile;
